name: first-pipe
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  first-job:
    name: "Meu primeiro job :-)"
    runs-on: ubuntu-latest
    steps:
      - name: "First Action"
        run: echo "Olá, funcionou minha primeira action!!!"
      - name: "Second Action with multiple runs"
        run: | 
          echo "Esta mensagem faz parte da segunda ação!"
          echo "Parabéns por ter criado o seu primeiro Workflow!"
      - name: "Uma mensagem agora usando o Python"
        run: |
          variavel = "Este é o resultado de um script em Python rodando da action"
          print(variavel)
        shell: python  
          
